### ISSUE TITLE
positive indices needed in sparse matrix

### ISSUE THREAD

**Issue by danielemarinazzo** [unfoldtoolbox/unfold#88] opened 2020-02-26 11:51 UTC
We sometimes get this error:

```
'Error using sparse
Index into matrix must be positive.

Error in uf_timeexpandDesignmat (line 173)
        Xdc = sparse(round(indrow_all(~removeIdx)),round(indcol_all(~removeIdx)),val_all(~removeIdx),dimFullX(1),dimFullX(2));

Error in CalculateERP (line 178)
    EEG = uf_timeexpandDesignmat(EEG,cfgTimeshift);'
```
Which refers to these lines

```
        '% delete everything larger than what its supposed to be
        dimFullX = [size(eventvec,2),cfg.windowlength*size(eventvec,1)];
        % We need to make sure the dimFullX are integers
        dimFullX = round(dimFullX);
        removeIdx = indrow_all>dimFullX(1) | indrow_all<=0;
        Xdc = sparse(round(indrow_all(~removeIdx)),round(indcol_all(~removeIdx)),val_all(~removeIdx),dimFullX(1),dimFullX(2));
        if cfg.sparse ==0
           fprintf('Converting sparse Xdc to full Xdc as requested\n')
           Xdc = full(Xdc);
        end
        basis = eye(cfg.windowlength);'
```

So in our case the indices are 0.4, 2.4 and so on, resulting in round(0.4)=0, and the consequent error.
What would you suggest? Just use "ceil" instead of "round", or exclude the first epoch, or something else?

thanks!

**Comment by behinger** [comment] 2020-02-26 12:05
thanks for the bug report.
clarification question: You have events that start at EEG.latency<0.5?

**Comment by danielemarinazzo** [comment] 2020-02-26 12:29
yes, basically we first divide our data in 20 seconds portions, then we
find events within them, and some of them are close (<.5 s) to the epoch
start.
I understand that typically "round" is not problematic since the baseline
is at least 0.5 seconds, right?
In our case we don't care too much about baseline, and we define an epoch
as [-.1 .4]s around the event.
What would you suggest in this case?

**Comment by behinger** [comment] 2020-02-26 13:59
I didn't fully understand your use case. So you run unfold for every 20s portion?
In any case, I think simply removing all entries =<0 of Xdc should work in this case. There is no data to model there in the first place.

**Comment by danielemarinazzo** [comment] 2020-02-26 14:39
Yes, basically we have longer time series with different events.
We split the long time series in different epochs in order to have
different samples of the ERP for within-subjects permutations.
indeed we will try to remove the entries =<0 of Xdc

**Comment by behinger** [comment] 2020-02-26 16:18
(ok I understand your usepoint). 

I just looked into it, but cannot reproduce the problem. 

Shouldn't  the second part of this        ```removeIdx = indrow_all>dimFullX(1) | indrow_all<=0;```
capture your case?

I.e. I tried to produce a minimal example:
```
EEGsim = simulate_test_case(testCase,'noise',0,'basis','box');
cfgDesign = [];

cfgDesign.coding = 'dummy';
cfgDesign.formula   = {'y~1'};
cfgDesign.eventtypes = {'stimulusA'};

EEGsim = uf_designmat(EEGsim,cfgDesign);

EEG = EEGsim;
EEG.event(1).latency = -1
EEG = uf_timeexpandDesignmat(EEG,'timelimits',[-1 2]);
```
But it crashes at a different part.


Looking through the code, I'm not sure exactly where the problem could arise. Do you have a reproducible example? Or some more information on which index (row I guess? or col) had to be rounded?

**Comment by behinger** [comment] 2020-03-10 08:34
sorry to bug you (ha!) - do you have any update on this?

**Comment by danielemarinazzo** [comment] 2020-03-10 08:56
Hi, not yet, we'll look better into it and hopefully send you a sample soon.
Thanks!

**Comment by behinger** [comment] 2021-07-02 14:37
bump - any news on this? Else I will close it for now

**Comment by danielemarinazzo** [comment] 2021-07-02 15:03
Hi Bene, yes please close it for now, but thanks for the bump, I'll should
get back to it eventually.

-- 

Daniele Marinazzo
Department of Data Analysis
Faculty of Psychology and Educational Sciences, Ghent University
Henri Dunantlaan 1, B-9000 Ghent, Belgium

+32 (0) 9 264 6375
http://users.ugent.be/~dmarinaz/

Twitter @dan_marinazzo

http://helpdesk.ugent.be/e-maildisclaimer.php

**Closed** 2021-07-02 15:42 UTC
Labels: bug
