### ISSUE TITLE
3rd party bug report: impute missing gives wrong results on Mac, correct on Windows

### ISSUE THREAD

**Issue by olafdimigen** [unfoldtoolbox/unfold#42] opened 2018-05-31 10:40 UTC
Moreno reports the following problem for Model containing a spline term

cfgDesign.formula = {'y ~ 1 + cat(factor) * cat(factor) + spl(predictor_saccade, 5)', 'y ~ 1 + cat(factor)'}; 

critical line: 
EEG_DC     = uf_imputeMissing(EEG_DC, cfg); 

Mac gives result: "no missing values"
But missing values found under windows.

I'll try to create a test dataset

**Comment by behinger** [comment] 2018-06-15 14:53
Any news on this?

**Comment by olafdimigen** [comment] 2018-06-27 14:10
Could not reproduce this under MAC OS Sierra, with Matlab R2018a. Very likely related to issue #46 and in no way Mac-specific.

**Comment by behinger** [comment] 2018-06-30 06:15
I don't think it is caused by this, or a different usecase was used under windows.

**Comment by behinger** [comment] 2018-09-10 11:08
This might have been related to the bug on NAN-handling. I will close this as I don't expect new information coming in

**Closed by behinger** 2018-09-10 11:08 UTC
Labels: compatibility_issue
